"""
tones.py - Preset INST Tone List da TR-8S (Ver.3.00), gerado por gen_tones.py.

NAO EDITAR NA MAO - regenerar com python3 gen_tones.py.

ID = BASE_ID + posicao na lista. E HIPOTESE (REFERENCIA 2.9):
o PDF nao numera; a base veio de o ARIA reservar 624-1023 aos
tones de usuario. A sessao de hardware confirma ou corrige -
se houver offset, mexer SO em BASE_ID.
"""

BASE_ID = 0     # hipotese: primeiro preset = id 0

TONES = [
    ('BD', '808 Bass1', 'ACB'),
    ('BD', '808 Bass2', 'ACB'),
    ('BD', '808 Bass1 Long', 'ACB'),
    ('BD', '808 Bass2 Long', 'ACB'),
    ('BD', '909 Bass1', 'ACB'),
    ('BD', '909 Bass2', 'ACB'),
    ('BD', '909 Attack Bass', 'ACB'),
    ('BD', '909 Low Bass', 'ACB'),
    ('BD', '707 Bass1/2', 'ACB'),
    ('BD', '707 Bass2/1', 'ACB'),
    ('BD', '606 Bass', 'ACB'),
    ('BD', 'CR78 Bass', 'ACB'),
    ('BD', 'FM Taste', 'FM'),
    ('BD', 'Zap Kick', 'FM'),
    ('BD', 'Simple Kick', 'FM'),
    ('BD', 'HolloKik', 'FM'),
    ('BD', 'WoodKick', 'FM'),
    ('BD', 'Clicker', 'FM'),
    ('BD', 'Knocker', 'FM'),
    ('BD', 'KikBass', 'FM'),
    ('BD', 'Zapdisk', 'FM'),
    ('BD', 'Hardcore', 'FM'),
    ('BD', 'BrokenJack', 'FM'),
    ('BD', 'FM Kick Model', 'FM'),
    ('BD', '626 Kick1', 'SAMPLE'),
    ('BD', '626 Kick2', 'SAMPLE'),
    ('BD', 'Lo-Bit Kick', 'SAMPLE'),
    ('BD', 'Hip Hop Kick1', 'SAMPLE'),
    ('BD', 'Hip Hop Kick2', 'SAMPLE'),
    ('BD', 'Break Beats Kick', 'SAMPLE'),
    ('BD', 'Pure Phat Kick', 'SAMPLE'),
    ('BD', 'DA Neat Kick', 'SAMPLE'),
    ('BD', 'DA Punchy Kick', 'SAMPLE'),
    ('BD', 'Big Room Kick1', 'SAMPLE'),
    ('BD', 'EDM 909 Kick1', 'SAMPLE'),
    ('BD', 'EDM 909 Kick2', 'SAMPLE'),
    ('BD', 'Sat Kick', 'SAMPLE'),
    ('BD', 'Synth Kick1', 'SAMPLE'),
    ('BD', 'Synth Kick2', 'SAMPLE'),
    ('BD', 'Synth Kick3', 'SAMPLE'),
    ('BD', 'Synth Kick4', 'SAMPLE'),
    ('BD', 'Big Room Kick2', 'SAMPLE'),
    ('BD', 'Big Room Kick3', 'SAMPLE'),
    ('BD', '106 Kick', 'SAMPLE'),
    ('BD', 'Big Room Kick4', 'SAMPLE'),
    ('BD', 'Tube Kick', 'SAMPLE'),
    ('BD', 'Modular Kick', 'SAMPLE'),
    ('BD', 'MG888 Kick', 'SAMPLE'),
    ('BD', 'MG888 RegiKick', 'SAMPLE'),
    ('SD', '808 Snare1', 'ACB'),
    ('SD', '808 Snare2', 'ACB'),
    ('SD', '909 Snare1', 'ACB'),
    ('SD', '909 Snare2', 'ACB'),
    ('SD', '909 Attack Snare', 'ACB'),
    ('SD', '707 Snare1/2', 'ACB'),
    ('SD', '707 Snare2/1', 'ACB'),
    ('SD', '606 Snare', 'ACB'),
    ('SD', 'CR78 Snare', 'ACB'),
    ('SD', 'Piccolo', 'FM'),
    ('SD', 'Circuitbent', 'FM'),
    ('SD', 'Simple Snare', 'FM'),
    ('SD', 'MidSnare', 'FM'),
    ('SD', 'Donk', 'FM'),
    ('SD', 'Dink', 'FM'),
    ('SD', 'Toned', 'FM'),
    ('SD', 'Oldschool', 'FM'),
    ('SD', 'Metalsheet', 'FM'),
    ('SD', 'Trashed', 'FM'),
    ('SD', 'Creeper', 'FM'),
    ('SD', 'FM Snare Model', 'FM'),
    ('SD', '626 Snare1', 'SAMPLE'),
    ('SD', '626 Snare2', 'SAMPLE'),
    ('SD', '626 Snare3', 'SAMPLE'),
    ('SD', 'Studio Snare1', 'SAMPLE'),
    ('SD', 'Studio Snare2', 'SAMPLE'),
    ('SD', 'Real Jazz Snare', 'SAMPLE'),
    ('SD', 'Dance Hall Snare', 'SAMPLE'),
    ('SD', 'EDM 909 Snare1', 'SAMPLE'),
    ('SD', 'EDM 909 Snare2', 'SAMPLE'),
    ('SD', '106 Snare1', 'SAMPLE'),
    ('SD', 'Hi Snare', 'SAMPLE'),
    ('SD', 'DA Chamber Snare', 'SAMPLE'),
    ('SD', 'DA Punchy Snare', 'SAMPLE'),
    ('SD', 'Dubstep Snare', 'SAMPLE'),
    ('SD', 'Big Room Snare1', 'SAMPLE'),
    ('SD', 'MG888 Snare1', 'SAMPLE'),
    ('SD', 'Sat Snare', 'SAMPLE'),
    ('SD', 'Tone&SynthSnare', 'SAMPLE'),
    ('SD', '106 Snare2', 'SAMPLE'),
    ('SD', '909 Dist. Snare', 'SAMPLE'),
    ('SD', '626 Dist. Snare1', 'SAMPLE'),
    ('SD', '626 Dist. Snare2', 'SAMPLE'),
    ('SD', 'Big Room Snare2', 'SAMPLE'),
    ('SD', 'Noise Snare', 'SAMPLE'),
    ('SD', 'Trap Snare', 'SAMPLE'),
    ('SD', 'Analog Snare1', 'SAMPLE'),
    ('SD', 'Analog Snare2', 'SAMPLE'),
    ('SD', 'Analog Snare3', 'SAMPLE'),
    ('SD', 'Modular Snare', 'SAMPLE'),
    ('SD', 'Layered Snare', 'SAMPLE'),
    ('SD', 'MG888 Snare2', 'SAMPLE'),
    ('SD', 'Snare & RealClap', 'SAMPLE'),
    ('SD', 'Snare&FingerSnap', 'SAMPLE'),
    ('SD', 'Snare & Syn.Clap', 'SAMPLE'),
    ('SD', 'Pure Phat Snare', 'SAMPLE'),
    ('SD', 'Snare & DistClap', 'SAMPLE'),
    ('SD', 'EDM Snare', 'SAMPLE'),
    ('SD', 'EDM Snare&Clap1', 'SAMPLE'),
    ('SD', 'EDM Snare&Clap2', 'SAMPLE'),
    ('SD', '909 Dist.Clap', 'SAMPLE'),
    ('SD', 'Industrial Snare', 'SAMPLE'),
    ('SD', 'Ring Snare', 'SAMPLE'),
    ('SD', 'Snare Scratch', 'SAMPLE'),
    ('TOM', '808 Low Tom', 'ACB'),
    ('TOM', '808 Mid Tom', 'ACB'),
    ('TOM', '808 High Tom', 'ACB'),
    ('TOM', '808 Noise Tom L', 'ACB'),
    ('TOM', '808 Noise Tom M', 'ACB'),
    ('TOM', '808 Noise Tom H', 'ACB'),
    ('TOM', '909 Low Tom', 'ACB'),
    ('TOM', '909 Mid Tom', 'ACB'),
    ('TOM', '909 High Tom', 'ACB'),
    ('TOM', '707 Low Tom', 'ACB'),
    ('TOM', '707 Mid Tom', 'ACB'),
    ('TOM', '707 High Tom', 'ACB'),
    ('TOM', '606 Floor Tom', 'ACB'),
    ('TOM', '606 Low Tom', 'ACB'),
    ('TOM', '606 High Tom', 'ACB'),
    ('TOM', '808 Full Tom', 'ACB'),
    ('TOM', '909 Full Tom', 'ACB'),
    ('TOM', '707 Full Tom', 'ACB'),
    ('TOM', '606 Full Tom', 'ACB'),
    ('TOM', 'FM Punch', 'FM'),
    ('TOM', 'FM Thud', 'FM'),
    ('TOM', 'Retro Tom', 'FM'),
    ('TOM', 'Migrane', 'FM'),
    ('TOM', 'Thump', 'FM'),
    ('TOM', 'FM Tom Model', 'FM'),
    ('TOM', '626 Low Tom1', 'SAMPLE'),
    ('TOM', '626 Mid Tom1', 'SAMPLE'),
    ('TOM', '626 High Tom1', 'SAMPLE'),
    ('TOM', '626 Low Tom2', 'SAMPLE'),
    ('TOM', '626 Mid Tom2', 'SAMPLE'),
    ('TOM', '626 High Tom2', 'SAMPLE'),
    ('TOM', 'Natural Tom', 'SAMPLE'),
    ('TOM', 'Can Tom', 'SAMPLE'),
    ('TOM', 'Analog Tom', 'SAMPLE'),
    ('TOM', 'Modular Tom', 'SAMPLE'),
    ('TOM', 'MG888 Low Tom', 'SAMPLE'),
    ('TOM', 'MG888 High Tom', 'SAMPLE'),
    ('TOM', 'Sat Mod Low Tom', 'SAMPLE'),
    ('TOM', 'Sat Mod High Tom', 'SAMPLE'),
    ('RS', '808 Rim Shot', 'ACB'),
    ('RS', '909 Rim Shot', 'ACB'),
    ('RS', '707 Rim Shot/CB', 'ACB'),
    ('RS', 'CR78 Rim Shot/CL', 'ACB'),
    ('RS', 'FM Rimshot', 'FM'),
    ('RS', '626 Rim Shot', 'SAMPLE'),
    ('RS', 'Cross Stick', 'SAMPLE'),
    ('RS', 'Wild Stick', 'SAMPLE'),
    ('RS', 'Lo-Fi Rim', 'SAMPLE'),
    ('RS', 'Real Rim', 'SAMPLE'),
    ('RS', 'MG888 Rim', 'SAMPLE'),
    ('RS', 'MG888 TrRim', 'SAMPLE'),
    ('RS', 'MG888 TrRimFlam', 'SAMPLE'),
    ('HC', '808 Hand Clap', 'ACB'),
    ('HC', '808 Finger Snap', 'ACB'),
    ('HC', '808 Noise Clap', 'ACB'),
    ('HC', '909 Hand Clap', 'ACB'),
    ('HC', '707 Hand Clap/TB', 'ACB'),
    ('HC', 'Twisted Clap', 'FM'),
    ('HC', 'Tinky Clap', 'FM'),
    ('HC', 'Crunch Clap', 'FM'),
    ('HC', 'FM Clap', 'FM'),
    ('HC', 'FM Clap Model', 'FM'),
    ('HC', '626 Hand Clap', 'SAMPLE'),
    ('HC', 'Claps Real', 'SAMPLE'),
    ('HC', 'Poly Clap', 'SAMPLE'),
    ('HC', 'Clap Stop', 'SAMPLE'),
    ('HC', 'Lacunal Clap', 'SAMPLE'),
    ('HC', 'Clap&FingerSnap', 'SAMPLE'),
    ('HC', 'EDM Clap', 'SAMPLE'),
    ('HC', 'Analog Clap1', 'SAMPLE'),
    ('HC', 'Analog Clap2', 'SAMPLE'),
    ('HC', 'Analog Clap3', 'SAMPLE'),
    ('HC', 'MG888 Clap', 'SAMPLE'),
    ('HC', 'MG888 MetalClap', 'SAMPLE'),
    ('HC', 'Afro Clap', 'SAMPLE'),
    ('HC', 'Reverse Clap', 'SAMPLE'),
    ('HC', 'Hip Hop Clap', 'SAMPLE'),
    ('HC', 'Craaak', 'SAMPLE'),
    ('HC', 'Scratch Clap', 'SAMPLE'),
    ('HC', 'Finger Snap1', 'SAMPLE'),
    ('HC', 'Finger Snap2', 'SAMPLE'),
    ('HC', 'StereoFingerSnap', 'SAMPLE'),
    ('CH_OH', '808 Closed HH', 'ACB'),
    ('CH_OH', '808 Open HH', 'ACB'),
    ('CH_OH', '909 Closed HH', 'ACB'),
    ('CH_OH', '909 Open HH', 'ACB'),
    ('CH_OH', '707 Closed HH', 'ACB'),
    ('CH_OH', '707 Open HH', 'ACB'),
    ('CH_OH', '606 Closed HH', 'ACB'),
    ('CH_OH', '606 Open HH', 'ACB'),
    ('CH_OH', 'CR78 Hi-Hat', 'ACB'),
    ('CH_OH', 'FM Metallic HH1', 'FM'),
    ('CH_OH', 'FM Hi-Hat', 'FM'),
    ('CH_OH', 'Tin man', 'FM'),
    ('CH_OH', 'FM Metallic HH2', 'FM'),
    ('CH_OH', '626 Closed HH', 'SAMPLE'),
    ('CH_OH', '626 Open HH', 'SAMPLE'),
    ('CH_OH', 'Med Closed HH', 'SAMPLE'),
    ('CH_OH', 'Med Open HH', 'SAMPLE'),
    ('CH_OH', 'Dry Closed HH', 'SAMPLE'),
    ('CH_OH', 'Dry Open HH', 'SAMPLE'),
    ('CH_OH', 'Comp Closed HH', 'SAMPLE'),
    ('CH_OH', 'Comp Open HH', 'SAMPLE'),
    ('CH_OH', 'Lo-Bit Closed HH', 'SAMPLE'),
    ('CH_OH', 'Lo-Bit Open HH', 'SAMPLE'),
    ('CH_OH', 'Closed 8bit HH', 'SAMPLE'),
    ('CH_OH', 'ShortNoiseMid HH', 'SAMPLE'),
    ('CH_OH', 'Sat HH', 'SAMPLE'),
    ('CH_OH', 'MG888 HH', 'SAMPLE'),
    ('CH_OH', 'Modular HH', 'SAMPLE'),
    ('CH_OH', 'Jazz Closed HH', 'SAMPLE'),
    ('CH_OH', 'Open Hard HH', 'SAMPLE'),
    ('CH_OH', 'Hi Open HH', 'SAMPLE'),
    ('CH_OH', 'Openopen HH', 'SAMPLE'),
    ('CH_OH', 'Vintage HH', 'SAMPLE'),
    ('CH_OH', 'Vinyl Open HH', 'SAMPLE'),
    ('CH_OH', 'Analog Closed HH', 'SAMPLE'),
    ('CH_OH', 'Analog Open HH', 'SAMPLE'),
    ('CH_OH', 'Sat Closed HH', 'SAMPLE'),
    ('CH_OH', 'Sat Open HH', 'SAMPLE'),
    ('CC_RC', '808 Cymbal', 'ACB'),
    ('CC_RC', '808 Gate Cymbal', 'ACB'),
    ('CC_RC', '909 Crash Cymbal', 'ACB'),
    ('CC_RC', '909 Ride Cymbal', 'ACB'),
    ('CC_RC', '707 Crash Cymbal', 'ACB'),
    ('CC_RC', '707 Ride Cymbal', 'ACB'),
    ('CC_RC', '606 Cymbal', 'ACB'),
    ('CC_RC', '606 Gate Cymbal', 'ACB'),
    ('CC_RC', 'CR78 Cymbal', 'ACB'),
    ('CC_RC', 'CR78 Metallic', 'ACB'),
    ('CC_RC', 'FM Cymbal1', 'FM'),
    ('CC_RC', 'FM Cymbal2', 'FM'),
    ('CC_RC', 'FM Cymbal Model', 'FM'),
    ('CC_RC', '626 Crash Cymbal', 'SAMPLE'),
    ('CC_RC', '626 Ride Cymbal', 'SAMPLE'),
    ('CC_RC', '626 Ride Cup', 'SAMPLE'),
    ('CC_RC', '626 China Cymbal', 'SAMPLE'),
    ('CC_RC', 'Standard16 Crash', 'SAMPLE'),
    ('CC_RC', 'StandardRideEdge', 'SAMPLE'),
    ('CC_RC', 'Stereo Cymbal', 'SAMPLE'),
    ('PERC1', '808 Low Conga', 'ACB'),
    ('PERC1', '808 Mid Conga', 'ACB'),
    ('PERC1', '808 High Conga', 'ACB'),
    ('PERC1', '727 HighBongo/LB', 'ACB'),
    ('PERC1', '727 LowBongo/HB', 'ACB'),
    ('PERC1', '727MtHiConga/OHC', 'ACB'),
    ('PERC1', '727OpHiConga/MHC', 'ACB'),
    ('PERC1', '727 Low Conga', 'ACB'),
    ('PERC1', '727 High Timbale', 'ACB'),
    ('PERC1', '727 Low Timbale', 'ACB'),
    ('PERC1', '808 Full Conga', 'ACB'),
    ('PERC1', 'CR78 Low Conga', 'ACB'),
    ('PERC1', 'CR78 Low Bongo', 'ACB'),
    ('PERC1', 'CR78 High Bongo', 'ACB'),
    ('PERC1', 'FM Conga', 'FM'),
    ('PERC1', 'FM Perc Model', 'FM'),
    ('PERC1', '626MuteHighConga', 'SAMPLE'),
    ('PERC1', '626OpenHighConga', 'SAMPLE'),
    ('PERC1', '626 Low Conga', 'SAMPLE'),
    ('PERC1', 'Sat Sine Conga', 'SAMPLE'),
    ('PERC1', 'Sat Sine Bongo', 'SAMPLE'),
    ('PERC1', '626 High Timbale', 'SAMPLE'),
    ('PERC1', '626 Low Timbale', 'SAMPLE'),
    ('PERC1', 'High Timbale', 'SAMPLE'),
    ('PERC1', 'Low Timbale', 'SAMPLE'),
    ('PERC1', 'SambaPercussion1', 'SAMPLE'),
    ('PERC1', 'Samba Bateria', 'SAMPLE'),
    ('PERC1', 'SambaPercussion2', 'SAMPLE'),
    ('PERC2', '808 Claves', 'ACB'),
    ('PERC2', 'CR78 Claves/RS', 'ACB'),
    ('PERC2', 'FM Claves', 'FM'),
    ('PERC2', '626 Claves', 'SAMPLE'),
    ('PERC2', 'High Claves', 'SAMPLE'),
    ('PERC2', 'MG888 Claves', 'SAMPLE'),
    ('PERC2', 'Ohkawa', 'SAMPLE'),
    ('PERC2', 'Block', 'SAMPLE'),
    ('PERC2', 'Castanets', 'SAMPLE'),
    ('PERC3', '808 Maracas', 'ACB'),
    ('PERC3', '707Tambourine/HC', 'ACB'),
    ('PERC3', '727 Cabasa/MA', 'ACB'),
    ('PERC3', '727 Maracas/CA', 'ACB'),
    ('PERC3', 'CR78 Maracas', 'ACB'),
    ('PERC3', 'CR78 Tamb 1/2', 'ACB'),
    ('PERC3', 'FM Shaker', 'FM'),
    ('PERC3', '626 Shaker', 'SAMPLE'),
    ('PERC3', 'Real Shaker', 'SAMPLE'),
    ('PERC3', 'Analog Shaker', 'SAMPLE'),
    ('PERC3', '626 Tambourine', 'SAMPLE'),
    ('PERC3', 'Tambourine', 'SAMPLE'),
    ('PERC3', 'Chekere', 'SAMPLE'),
    ('PERC3', 'AfroDrum Rat', 'SAMPLE'),
    ('PERC4', '808 Cowbell', 'ACB'),
    ('PERC4', '707 Cowbell/RS', 'ACB'),
    ('PERC4', '727 HighAgogo/LA', 'ACB'),
    ('PERC4', '727 Low Agogo/HA', 'ACB'),
    ('PERC4', 'CR78 Cowbell', 'ACB'),
    ('PERC4', 'Bendy Bell', 'FM'),
    ('PERC4', 'FM Cowbell', 'FM'),
    ('PERC4', 'Detuned CB', 'FM'),
    ('PERC4', '626 Cowbell', 'SAMPLE'),
    ('PERC4', 'Cowbell', 'SAMPLE'),
    ('PERC4', 'Tin Cowbell', 'SAMPLE'),
    ('PERC4', '626 High Agogo', 'SAMPLE'),
    ('PERC4', '626 Low Agogo', 'SAMPLE'),
    ('PERC4', 'Open Triangle', 'SAMPLE'),
    ('PERC4', 'Funky Triangle', 'SAMPLE'),
    ('PERC5', '727 ShortWhistle', 'ACB'),
    ('PERC5', '727 Long Whistle', 'ACB'),
    ('PERC5', '727 Quijada', 'ACB'),
    ('PERC5', '727 Star Chime', 'ACB'),
    ('PERC5', 'CR78 Guiro 1/2', 'ACB'),
    ('PERC5', 'FM Whistle', 'FM'),
    ('PERC5', 'Jingle Bell', 'SAMPLE'),
    ('PERC5', 'Udu Pot Long', 'SAMPLE'),
    ('PERC5', 'Udu Pot Short', 'SAMPLE'),
    ('PERC5', 'Udu Pot Mute', 'SAMPLE'),
    ('FX_HIT', 'Stressor', 'FM'),
    ('FX_HIT', 'Detuned Syn', 'FM'),
    ('FX_HIT', 'Beeow', 'FM'),
    ('FX_HIT', 'Filler', 'FM'),
    ('FX_HIT', 'TriTone', 'FM'),
    ('FX_HIT', 'GhostChord', 'FM'),
    ('FX_HIT', 'GlassBrush', 'FM'),
    ('FX_HIT', 'FM Metallic Perc', 'FM'),
    ('FX_HIT', 'LowBell', 'FM'),
    ('FX_HIT', 'HiBell', 'FM'),
    ('FX_HIT', 'AnalogMetalPerc1', 'SAMPLE'),
    ('FX_HIT', 'AnalogMetalPerc2', 'SAMPLE'),
    ('FX_HIT', 'Mental Perc', 'SAMPLE'),
    ('FX_HIT', 'Dr.Beat', 'SAMPLE'),
    ('FX_HIT', 'PC-2 Machine', 'SAMPLE'),
    ('FX_HIT', 'Feedback Stab', 'SAMPLE'),
    ('FX_HIT', '1971 SpringBlip', 'SAMPLE'),
    ('FX_HIT', '1971 Doctor', 'SAMPLE'),
    ('FX_HIT', '1971 Phone', 'SAMPLE'),
    ('FX_HIT', 'Modular Sweep', 'SAMPLE'),
    ('FX_HIT', 'Modular FX Dly', 'SAMPLE'),
    ('FX_HIT', 'PC-2 Spacers', 'SAMPLE'),
    ('FX_HIT', 'Ring FX', 'SAMPLE'),
    ('FX_HIT', '1971 Fall', 'SAMPLE'),
    ('FX_HIT', 'Modular FX1', 'SAMPLE'),
    ('FX_HIT', 'Modular FX2', 'SAMPLE'),
    ('FX_HIT', 'MG888 FutureShot', 'SAMPLE'),
    ('FX_HIT', 'SH2 S Zap', 'SAMPLE'),
    ('FX_HIT', '1971 Dong', 'SAMPLE'),
    ('FX_HIT', 'Sat Stab', 'SAMPLE'),
    ('FX_HIT', 'Pong1', 'SAMPLE'),
    ('FX_HIT', 'Pong2', 'SAMPLE'),
    ('FX_HIT', 'Boing', 'SAMPLE'),
    ('FX_HIT', 'Jungle Beep', 'SAMPLE'),
    ('FX_HIT', 'Tape Stop', 'SAMPLE'),
    ('FX_HIT', 'Techno Scene', 'SAMPLE'),
    ('FX_HIT', 'P.Phatt Hit', 'SAMPLE'),
    ('FX_HIT', 'Hit & Drum', 'SAMPLE'),
    ('FX_HIT', 'Spoon Hit', 'SAMPLE'),
    ('FX_HIT', 'Elec Sizzle', 'SAMPLE'),
    ('FX_HIT', 'Industrial Hit1', 'SAMPLE'),
    ('FX_HIT', 'Industrial Hit2', 'SAMPLE'),
    ('FX_HIT', 'PCM Press', 'SAMPLE'),
    ('FX_HIT', 'Thrill', 'SAMPLE'),
    ('FX_HIT', 'ElectricDunk', 'SAMPLE'),
    ('FX_HIT', 'Construction', 'SAMPLE'),
    ('FX_HIT', 'Sawing', 'SAMPLE'),
    ('FX_HIT', 'Compress Start', 'SAMPLE'),
    ('FX_HIT', 'Jack Hammer', 'SAMPLE'),
    ('FX_HIT', 'Machine Noise', 'SAMPLE'),
    ('FX_HIT', 'Metal Bang', 'SAMPLE'),
    ('FX_HIT', 'Metallic Shot', 'SAMPLE'),
    ('FX_HIT', 'Tom Noise', 'SAMPLE'),
    ('FX_HIT', 'Hi Dist Short', 'SAMPLE'),
    ('FX_HIT', 'DigiAttack', 'SAMPLE'),
    ('FX_HIT', 'Vinyl Noise', 'SAMPLE'),
    ('FX_HIT', 'Glass', 'SAMPLE'),
    ('FX_HIT', 'Rev 626 Crash', 'SAMPLE'),
    ('FX_HIT', 'Rev 626 Ride', 'SAMPLE'),
    ('FX_HIT', 'Rev 626 Cup', 'SAMPLE'),
    ('FX_HIT', 'Rev 626 China', 'SAMPLE'),
    ('FX_HIT', 'Rev Stereo Cym', 'SAMPLE'),
    ('FX_HIT', 'Rev Analog Tom', 'SAMPLE'),
    ('FX_HIT', 'Rev Natural Tom', 'SAMPLE'),
    ('FX_HIT', 'Flute FX', 'SAMPLE'),
    ('FX_HIT', 'Tube FX', 'SAMPLE'),
    ('FX_HIT', 'Voice Bells', 'SAMPLE'),
    ('VOICE', 'FM Deep Voice', 'FM'),
    ('VOICE', 'Ouh', 'SAMPLE'),
    ('VOICE', 'Hoo!', 'SAMPLE'),
    ('VOICE', 'Uhha', 'SAMPLE'),
    ('VOICE', 'Eh', 'SAMPLE'),
    ('VOICE', 'Oh!', 'SAMPLE'),
    ('VOICE', 'DA Break', 'SAMPLE'),
    ('VOICE', 'DA VT Check', 'SAMPLE'),
    ('VOICE', 'DA VT Hey', 'SAMPLE'),
    ('VOICE', 'DA VT Oh', 'SAMPLE'),
    ('VOICE', 'DA VP Go', 'SAMPLE'),
    ('VOICE', 'DA VP Move', 'SAMPLE'),
    ('VOICE', 'Voice FX', 'SAMPLE'),
    ('VOICE', 'Vocoder A', 'SAMPLE'),
    ('VOICE', 'Vocoder Dance', 'SAMPLE'),
    ('VOICE', 'Aah Formant', 'SAMPLE'),
    ('VOICE', 'Eeh Formant', 'SAMPLE'),
    ('VOICE', 'Iih Formant', 'SAMPLE'),
    ('VOICE', 'Ooh Formant', 'SAMPLE'),
    ('VOICE', 'Uuh Formant', 'SAMPLE'),
    ('SYNTH1', 'FM Pluck', 'FM'),
    ('SYNTH1', 'FM Dual Pluck', 'FM'),
    ('SYNTH1', '5th Synth', 'FM'),
    ('SYNTH1', 'Soft Pad', 'SAMPLE'),
    ('SYNTH1', 'Synth Strings', 'SAMPLE'),
    ('SYNTH1', 'ElectroHouse Syn', 'SAMPLE'),
    ('SYNTH1', 'EDM Bend Up Lead', 'SAMPLE'),
    ('SYNTH1', 'EDM Voice Lead', 'SAMPLE'),
    ('SYNTH1', 'Dubstep Lead', 'SAMPLE'),
    ('SYNTH1', 'Percussive Lead', 'SAMPLE'),
    ('SYNTH1', 'FutureHouseLead1', 'SAMPLE'),
    ('SYNTH1', 'FutureHouseLead2', 'SAMPLE'),
    ('SYNTH1', 'Synth Calliope', 'SAMPLE'),
    ('SYNTH1', 'Synth Pluck1', 'SAMPLE'),
    ('SYNTH1', 'Synth Pluck2', 'SAMPLE'),
    ('SYNTH1', 'Trap Synth1', 'SAMPLE'),
    ('SYNTH1', 'Trap Synth2', 'SAMPLE'),
    ('SYNTH1', 'Trap Horn1', 'SAMPLE'),
    ('SYNTH1', 'Trap Horn2', 'SAMPLE'),
    ('SYNTH2', 'OSC FM', 'FM'),
    ('SYNTH2', 'OSC FM2', 'FM'),
    ('SYNTH2', 'OSC FM 5th', 'FM'),
    ('SYNTH2', 'OSC Sine Low', 'SAMPLE'),
    ('SYNTH2', 'OSC Sine High', 'SAMPLE'),
    ('SYNTH2', 'OSC Cosine Low', 'SAMPLE'),
    ('SYNTH2', 'OSC Cosine High', 'SAMPLE'),
    ('SYNTH2', 'OSC Tri1 Low', 'SAMPLE'),
    ('SYNTH2', 'OSC Tri1 High', 'SAMPLE'),
    ('SYNTH2', 'OSC Tri2 Low', 'SAMPLE'),
    ('SYNTH2', 'OSC Tri2 High', 'SAMPLE'),
    ('SYNTH2', 'OSC Square Low', 'SAMPLE'),
    ('SYNTH2', 'OSC Square High', 'SAMPLE'),
    ('SYNTH2', 'OSC Pulse1 Low', 'SAMPLE'),
    ('SYNTH2', 'OSC Pulse1 High', 'SAMPLE'),
    ('SYNTH2', 'OSC Pulse2 Low', 'SAMPLE'),
    ('SYNTH2', 'OSC Pulse2 High', 'SAMPLE'),
    ('SYNTH2', 'OSC Saw Low', 'SAMPLE'),
    ('SYNTH2', 'OSC Saw High', 'SAMPLE'),
    ('SYNTH2', 'Detune Saw Low', 'SAMPLE'),
    ('SYNTH2', 'Detune Saw High', 'SAMPLE'),
    ('SYNTH2', 'Super Saw1', 'SAMPLE'),
    ('SYNTH2', 'Super Saw2', 'SAMPLE'),
    ('SYNTH2', 'Super Saw1 5th', 'SAMPLE'),
    ('SYNTH2', 'Super Saw2 5th', 'SAMPLE'),
    ('SYNTH2', 'White Noise1', 'SAMPLE'),
    ('SYNTH2', 'White Noise2', 'SAMPLE'),
    ('SYNTH2', 'White Noise3', 'SAMPLE'),
    ('BASS', '808 Chromatic Bs', 'ACB'),
    ('BASS', 'FM Bass', 'FM'),
    ('BASS', 'BassSwoopMaj', 'FM'),
    ('BASS', 'Sustnd808Bs', 'SAMPLE'),
    ('BASS', 'DistSustnd808Bs1', 'SAMPLE'),
    ('BASS', 'DistSustnd808Bs2', 'SAMPLE'),
    ('BASS', 'DistSustnd808Bs3', 'SAMPLE'),
    ('BASS', 'DistSustnd808Bs4', 'SAMPLE'),
    ('BASS', 'Heavy Future Bs1', 'SAMPLE'),
    ('BASS', 'Heavy Future Bs2', 'SAMPLE'),
    ('BASS', 'Organ Bass', 'SAMPLE'),
    ('BASS', 'Percussive Bass', 'SAMPLE'),
    ('BASS', 'Prog.Trance Bass', 'SAMPLE'),
    ('BASS', 'Deep SH Bass', 'SAMPLE'),
    ('BASS', 'Electro House Bs', 'SAMPLE'),
    ('BASS', 'Yeah Bass', 'SAMPLE'),
    ('BASS', 'Yigh Bass', 'SAMPLE'),
    ('BASS', 'Mute Bass', 'SAMPLE'),
    ('SCALED', 'FM Mallet Perc.', 'FM'),
    ('SCALED', 'Ac.Piano Mid', 'SAMPLE'),
    ('SCALED', 'Ac.Piano High', 'SAMPLE'),
    ('SCALED', 'E.Piano Mid', 'SAMPLE'),
    ('SCALED', 'E.Piano High', 'SAMPLE'),
    ('SCALED', 'Kalimba Mid', 'SAMPLE'),
    ('SCALED', 'Kalimba High', 'SAMPLE'),
    ('SCALED', 'Tropical Mallet', 'SAMPLE'),
    ('SCALED', 'Pizzi Techno', 'SAMPLE'),
    ('SCALED', 'Strings Attack', 'SAMPLE'),
    ('SCALED', 'LA BrassLow Oct', 'SAMPLE'),
    ('SCALED', 'LA BrassHigh Oct', 'SAMPLE'),
    ('SCALED', 'LA BrassLow 5th', 'SAMPLE'),
    ('SCALED', 'LA BrassHigh 5th', 'SAMPLE'),
    ('SCALED', 'Didgeridoo', 'SAMPLE'),
    ('CHORD', 'FM Synth Chord', 'FM'),
    ('CHORD', 'HouseChordPiano', 'SAMPLE'),
    ('CHORD', 'E.Piano Maj 9th', 'SAMPLE'),
    ('CHORD', 'E.Piano Hit', 'SAMPLE'),
    ('CHORD', 'E.Piano Maj 11th', 'SAMPLE'),
    ('CHORD', 'Strings Maj 11th', 'SAMPLE'),
    ('CHORD', 'Open Str', 'SAMPLE'),
    ('CHORD', 'Wah Mute', 'SAMPLE'),
    ('CHORD', 'Percussive Chord', 'SAMPLE'),
    ('CHORD', 'DA D50 Chord', 'SAMPLE'),
    ('CHORD', 'Atmosphere', 'SAMPLE'),
    ('CHORD', 'DA SH Chord', 'SAMPLE'),
    ('CHORD', 'SoftPad minor7th', 'SAMPLE'),
    ('CHORD', 'SoftPad major7th', 'SAMPLE'),
    ('CHORD', 'SoftPad 7th', 'SAMPLE'),
    ('CHORD', 'Syn.Str minor7th', 'SAMPLE'),
    ('CHORD', 'Syn.Str major7th', 'SAMPLE'),
    ('CHORD', 'Syn.Str 7th', 'SAMPLE'),
]


def tone_id(pos):
    return BASE_ID + pos


def nome_do_id(tid):
    """Nome pela hipotese de id, ou None se fora da lista."""
    pos = tid - BASE_ID
    if 0 <= pos < len(TONES):
        cat, nome, tipo = TONES[pos]
        return f"{nome} ({cat} {tipo})"
    return None


def por_categoria():
    grupos = {}
    for pos, (cat, nome, tipo) in enumerate(TONES):
        grupos.setdefault(cat, []).append((pos, nome, tipo))
    return grupos
