"""
tones.py - a lista de tones da TR-8S, gerada por gen_tones.py.

NAO EDITAR NA MAO.

Fonte: ToneDetailsConfigTable.dat, de dentro do TR-EDITOR. O id de SysEx e o
NUMBER da tabela MENOS UM - provado contra os 22 tone ids lidos dos kits
TR-808 e TR-707 da maquina do Luan (REFERENCIA 2.9).

Os ids NAO sao contiguos: a Roland deixa buracos entre as familias. Por isso
isto e uma lista de tuplas com o id dentro, e nao uma lista indexada por
posicao - foi confundir as duas coisas que carregou o tone errado em
15/08/2026.

    (id, categoria, nome, tipo, maquina)
"""

TONES = [
    (0, 'BD', '808 Bass1', 'ACB', 'TR-808'),
    (1, 'BD', '808 Bass2', 'ACB', 'TR-808'),
    (2, 'BD', '808 Bass1 Long', 'ACB', 'TR-808'),
    (3, 'BD', '808 Bass2 Long', 'ACB', 'TR-808'),
    (4, 'SD', '808 Snare1', 'ACB', 'TR-808'),
    (5, 'SD', '808 Snare2', 'ACB', 'TR-808'),
    (6, 'TOM', '808 Low Tom', 'ACB', 'TR-808'),
    (7, 'TOM', '808 Mid Tom', 'ACB', 'TR-808'),
    (8, 'TOM', '808 High Tom', 'ACB', 'TR-808'),
    (9, 'PERC1', '808 Low Conga', 'ACB', 'TR-808'),
    (10, 'PERC1', '808 Mid Conga', 'ACB', 'TR-808'),
    (11, 'PERC1', '808 High Conga', 'ACB', 'TR-808'),
    (12, 'TOM', '808 Noise Tom L', 'ACB', 'TR-808'),
    (13, 'TOM', '808 Noise Tom M', 'ACB', 'TR-808'),
    (14, 'TOM', '808 Noise Tom H', 'ACB', 'TR-808'),
    (15, 'RS', '808 Rim Shot', 'ACB', 'TR-808'),
    (16, 'PERC2', '808 Claves', 'ACB', 'TR-808'),
    (17, 'HC', '808 Hand Clap', 'ACB', 'TR-808'),
    (18, 'PERC3', '808 Maracas', 'ACB', 'TR-808'),
    (19, 'HC', '808 Finger Snap', 'ACB', 'TR-808'),
    (20, 'HC', '808 Noise Clap', 'ACB', 'TR-808'),
    (21, 'CH_OH', '808 Closed HH', 'ACB', 'TR-808'),
    (22, 'CH_OH', '808 Open HH', 'ACB', 'TR-808'),
    (23, 'CC_RC', '808 Cymbal', 'ACB', 'TR-808'),
    (24, 'CC_RC', '808 Gate Cymbal', 'ACB', 'TR-808'),
    (25, 'PERC4', '808 Cowbell', 'ACB', 'TR-808'),
    (26, 'BD', '909 Bass1', 'ACB', 'TR-909'),
    (27, 'BD', '909 Bass2', 'ACB', 'TR-909'),
    (28, 'BD', '909 Attack Bass', 'ACB', 'TR-909'),
    (29, 'BD', '909 Low Bass', 'ACB', 'TR-909'),
    (30, 'SD', '909 Snare1', 'ACB', 'TR-909'),
    (31, 'SD', '909 Snare2', 'ACB', 'TR-909'),
    (32, 'SD', '909 Attack Snare', 'ACB', 'TR-909'),
    (33, 'TOM', '909 Low Tom', 'ACB', 'TR-909'),
    (34, 'TOM', '909 Mid Tom', 'ACB', 'TR-909'),
    (35, 'TOM', '909 High Tom', 'ACB', 'TR-909'),
    (36, 'RS', '909 Rim Shot', 'ACB', 'TR-909'),
    (37, 'HC', '909 Hand Clap', 'ACB', 'TR-909'),
    (38, 'CH_OH', '909 Closed HH', 'ACB', 'TR-909'),
    (39, 'CH_OH', '909 Open HH', 'ACB', 'TR-909'),
    (40, 'CC_RC', '909 Crash Cymbal', 'ACB', 'TR-909'),
    (41, 'CC_RC', '909 Ride Cymbal', 'ACB', 'TR-909'),
    (42, 'BD', '707 Bass1/2', 'ACB', 'TR-707'),
    (43, 'BD', '707 Bass2/1', 'ACB', 'TR-707'),
    (44, 'SD', '707 Snare1/2', 'ACB', 'TR-707'),
    (45, 'SD', '707 Snare2/1', 'ACB', 'TR-707'),
    (46, 'TOM', '707 Low Tom', 'ACB', 'TR-707'),
    (47, 'TOM', '707 Mid Tom', 'ACB', 'TR-707'),
    (48, 'TOM', '707 High Tom', 'ACB', 'TR-707'),
    (49, 'RS', '707 Rim Shot/CB', 'ACB', 'TR-707'),
    (50, 'PERC4', '707 Cowbell/RS', 'ACB', 'TR-707'),
    (51, 'HC', '707 Hand Clap/TB', 'ACB', 'TR-707'),
    (52, 'PERC3', '707Tambourine/HC', 'ACB', 'TR-707'),
    (53, 'CH_OH', '707 Closed HH', 'ACB', 'TR-707'),
    (54, 'CH_OH', '707 Open HH', 'ACB', 'TR-707'),
    (55, 'CC_RC', '707 Crash Cymbal', 'ACB', 'TR-707'),
    (56, 'CC_RC', '707 Ride Cymbal', 'ACB', 'TR-707'),
    (57, 'PERC1', '727 HighBongo/LB', 'ACB', 'TR-727'),
    (58, 'PERC1', '727 LowBongo/HB', 'ACB', 'TR-727'),
    (59, 'PERC1', '727MtHiConga/OHC', 'ACB', 'TR-727'),
    (60, 'PERC1', '727OpHiConga/MHC', 'ACB', 'TR-727'),
    (61, 'PERC1', '727 Low Conga', 'ACB', 'TR-727'),
    (62, 'PERC1', '727 High Timbale', 'ACB', 'TR-727'),
    (63, 'PERC1', '727 Low Timbale', 'ACB', 'TR-727'),
    (64, 'PERC4', '727 HighAgogo/LA', 'ACB', 'TR-727'),
    (65, 'PERC4', '727 Low Agogo/HA', 'ACB', 'TR-727'),
    (66, 'PERC3', '727 Cabasa/MA', 'ACB', 'TR-727'),
    (67, 'PERC3', '727 Maracas/CA', 'ACB', 'TR-727'),
    (68, 'PERC5', '727 ShortWhistle', 'ACB', 'TR-727'),
    (69, 'PERC5', '727 Long Whistle', 'ACB', 'TR-727'),
    (70, 'PERC5', '727 Quijada', 'ACB', 'TR-727'),
    (71, 'PERC5', '727 Star Chime', 'ACB', 'TR-727'),
    (72, 'BD', '606 Bass', 'ACB', 'TR-606'),
    (73, 'SD', '606 Snare', 'ACB', 'TR-606'),
    (74, 'TOM', '606 Floor Tom', 'ACB', 'TR-606'),
    (75, 'TOM', '606 Low Tom', 'ACB', 'TR-606'),
    (76, 'TOM', '606 High Tom', 'ACB', 'TR-606'),
    (77, 'CH_OH', '606 Closed HH', 'ACB', 'TR-606'),
    (78, 'CH_OH', '606 Open HH', 'ACB', 'TR-606'),
    (79, 'CC_RC', '606 Cymbal', 'ACB', 'TR-606'),
    (80, 'CC_RC', '606 Gate Cymbal', 'ACB', 'TR-606'),
    (81, 'TOM', '808 Full Tom', 'ACB', 'TR-808'),
    (82, 'PERC1', '808 Full Conga', 'ACB', 'TR-808'),
    (83, 'TOM', '909 Full Tom', 'ACB', 'TR-909'),
    (84, 'TOM', '707 Full Tom', 'ACB', 'TR-707'),
    (85, 'TOM', '606 Full Tom', 'ACB', 'TR-606'),
    (86, 'BD', 'FM Taste', 'FM', 'FM'),
    (87, 'BD', 'Zap Kick', 'FM', 'FM'),
    (88, 'BD', 'Simple Kick', 'FM', 'FM'),
    (89, 'BD', 'HolloKik', 'FM', 'FM'),
    (90, 'BD', 'WoodKick', 'FM', 'FM'),
    (91, 'BD', 'Clicker', 'FM', 'FM'),
    (92, 'BD', 'Knocker', 'FM', 'FM'),
    (93, 'BD', 'KikBass', 'FM', 'FM'),
    (94, 'BD', 'Zapdisk', 'FM', 'FM'),
    (95, 'BD', 'Hardcore', 'FM', 'FM'),
    (96, 'BD', 'BrokenJack', 'FM', 'FM'),
    (97, 'SD', 'Piccolo', 'FM', 'FM'),
    (98, 'SD', 'Circuitbent', 'FM', 'FM'),
    (99, 'SD', 'Simple Snare', 'FM', 'FM'),
    (100, 'SD', 'MidSnare', 'FM', 'FM'),
    (101, 'SD', 'Donk', 'FM', 'FM'),
    (102, 'SD', 'Dink', 'FM', 'FM'),
    (103, 'SD', 'Toned', 'FM', 'FM'),
    (104, 'SD', 'Oldschool', 'FM', 'FM'),
    (105, 'SD', 'Metalsheet', 'FM', 'FM'),
    (106, 'SD', 'Trashed', 'FM', 'FM'),
    (107, 'SD', 'Creeper', 'FM', 'FM'),
    (108, 'TOM', 'FM Punch', 'FM', 'FM'),
    (109, 'TOM', 'FM Thud', 'FM', 'FM'),
    (110, 'TOM', 'Retro Tom', 'FM', 'FM'),
    (111, 'TOM', 'Migrane', 'FM', 'FM'),
    (112, 'TOM', 'Thump', 'FM', 'FM'),
    (113, 'RS', 'FM Rimshot', 'FM', 'FM'),
    (114, 'HC', 'Twisted Clap', 'FM', 'FM'),
    (115, 'HC', 'Tinky Clap', 'FM', 'FM'),
    (116, 'HC', 'Crunch Clap', 'FM', 'FM'),
    (117, 'HC', 'FM Clap', 'FM', 'FM'),
    (118, 'CH_OH', 'FM Metallic HH1', 'FM', 'FM'),
    (119, 'CH_OH', 'FM Hi-Hat', 'FM', 'FM'),
    (120, 'CH_OH', 'Tin man', 'FM', 'FM'),
    (121, 'CH_OH', 'FM Metallic HH2', 'FM', 'FM'),
    (122, 'CC_RC', 'FM Cymbal1', 'FM', 'FM'),
    (123, 'CC_RC', 'FM Cymbal2', 'FM', 'FM'),
    (124, 'PERC1', 'FM Conga', 'FM', 'FM'),
    (125, 'PERC2', 'FM Claves', 'FM', 'FM'),
    (126, 'PERC3', 'FM Shaker', 'FM', 'FM'),
    (127, 'PERC4', 'Bendy Bell', 'FM', 'FM'),
    (128, 'PERC4', 'FM Cowbell', 'FM', 'FM'),
    (129, 'PERC4', 'Detuned CB', 'FM', 'FM'),
    (130, 'PERC5', 'FM Whistle', 'FM', 'FM'),
    (131, 'FX_HIT', 'Stressor', 'FM', 'FM'),
    (132, 'FX_HIT', 'Detuned Syn', 'FM', 'FM'),
    (133, 'FX_HIT', 'Beeow', 'FM', 'FM'),
    (134, 'FX_HIT', 'Filler', 'FM', 'FM'),
    (135, 'FX_HIT', 'TriTone', 'FM', 'FM'),
    (136, 'FX_HIT', 'GhostChord', 'FM', 'FM'),
    (137, 'FX_HIT', 'GlassBrush', 'FM', 'FM'),
    (138, 'FX_HIT', 'FM Metallic Perc', 'FM', 'FM'),
    (139, 'FX_HIT', 'LowBell', 'FM', 'FM'),
    (140, 'FX_HIT', 'HiBell', 'FM', 'FM'),
    (141, 'VOICE', 'FM Deep Voice', 'FM', 'FM'),
    (142, 'SYNTH1', 'FM Pluck', 'FM', 'FM'),
    (143, 'SYNTH1', 'FM Dual Pluck', 'FM', 'FM'),
    (144, 'SYNTH1', '5th Synth', 'FM', 'FM'),
    (145, 'SYNTH2', 'OSC FM', 'FM', 'FM'),
    (146, 'SYNTH2', 'OSC FM2', 'FM', 'FM'),
    (147, 'SYNTH2', 'OSC FM 5th', 'FM', 'FM'),
    (148, 'BASS', 'FM Bass', 'FM', 'FM'),
    (149, 'BASS', 'BassSwoopMaj', 'FM', 'FM'),
    (150, 'SCALED', 'FM Mallet Perc.', 'FM', 'FM'),
    (151, 'CHORD', 'FM Synth Chord', 'FM', 'FM'),
    (152, 'BD', 'FM Kick Model', 'FM', 'FMMOD'),
    (153, 'SD', 'FM Snare Model', 'FM', 'FMMOD'),
    (154, 'TOM', 'FM Tom Model', 'FM', 'FMMOD'),
    (155, 'HC', 'FM Clap Model', 'FM', 'FMMOD'),
    (156, 'CC_RC', 'FM Cymbal Model', 'FM', 'FMMOD'),
    (157, 'PERC1', 'FM Perc Model', 'FM', 'FMMOD'),
    (158, 'BASS', '808 Chromatic Bs', 'ACB', 'TR-808'),
    (159, 'BD', 'CR78 Bass', 'ACB', 'CR-78'),
    (160, 'SD', 'CR78 Snare', 'ACB', 'CR-78'),
    (161, 'RS', 'CR78 Rim Shot/CL', 'ACB', 'CR-78'),
    (162, 'CH_OH', 'CR78 Hi-Hat', 'ACB', 'CR-78'),
    (163, 'CC_RC', 'CR78 Cymbal', 'ACB', 'CR-78'),
    (164, 'CC_RC', 'CR78 Metallic', 'ACB', 'CR-78'),
    (165, 'PERC1', 'CR78 Low Conga', 'ACB', 'CR-78'),
    (166, 'PERC1', 'CR78 Low Bongo', 'ACB', 'CR-78'),
    (167, 'PERC1', 'CR78 High Bongo', 'ACB', 'CR-78'),
    (168, 'PERC2', 'CR78 Claves/RS', 'ACB', 'CR-78'),
    (169, 'PERC3', 'CR78 Maracas', 'ACB', 'CR-78'),
    (170, 'PERC3', 'CR78 Tamb 1/2', 'ACB', 'CR-78'),
    (171, 'PERC5', 'CR78 Guiro 1/2', 'ACB', 'CR-78'),
    (172, 'PERC4', 'CR78 Cowbell', 'ACB', 'CR-78'),
    (181, 'BD', '626 Kick1', 'PCM', 'TR-626'),
    (182, 'BD', '626 Kick2', 'PCM', 'TR-626'),
    (183, 'BD', 'Lo-Bit Kick', 'PCM', 'PCM'),
    (184, 'BD', 'Hip Hop Kick1', 'PCM', 'PCM'),
    (185, 'BD', 'Hip Hop Kick2', 'PCM', 'PCM'),
    (186, 'BD', 'Break Beats Kick', 'PCM', 'PCM'),
    (187, 'BD', 'Pure Phat Kick', 'PCM', 'PCM'),
    (188, 'BD', 'DA Neat Kick', 'PCM', 'PCM'),
    (189, 'BD', 'DA Punchy Kick', 'PCM', 'PCM'),
    (190, 'BD', 'Big Room Kick1', 'PCM', 'PCM'),
    (191, 'BD', 'EDM 909 Kick1', 'PCM', 'PCM'),
    (192, 'BD', 'EDM 909 Kick2', 'PCM', 'PCM'),
    (193, 'BD', 'Sat Kick', 'PCM', 'PCM'),
    (194, 'BD', 'Synth Kick1', 'PCM', 'PCM'),
    (195, 'BD', 'Synth Kick2', 'PCM', 'PCM'),
    (196, 'BD', 'Synth Kick3', 'PCM', 'PCM'),
    (197, 'BD', 'Synth Kick4', 'PCM', 'PCM'),
    (198, 'BD', 'Big Room Kick2', 'PCM', 'PCM'),
    (199, 'BD', 'Big Room Kick3', 'PCM', 'PCM'),
    (200, 'BD', '106 Kick', 'PCM', 'PCM'),
    (201, 'BD', 'Big Room Kick4', 'PCM', 'PCM'),
    (202, 'BD', 'Tube Kick', 'PCM', 'PCM'),
    (203, 'BD', 'Modular Kick', 'PCM', 'PCM'),
    (204, 'BD', 'MG888 Kick', 'PCM', 'PCM'),
    (205, 'BD', 'MG888 RegiKick', 'PCM', 'PCM'),
    (206, 'SD', '626 Snare1', 'PCM', 'TR-626'),
    (207, 'SD', '626 Snare2', 'PCM', 'TR-626'),
    (208, 'SD', '626 Snare3', 'PCM', 'TR-626'),
    (209, 'SD', 'Studio Snare1', 'PCM', 'PCM'),
    (210, 'SD', 'Studio Snare2', 'PCM', 'PCM'),
    (211, 'SD', 'Real Jazz Snare', 'PCM', 'PCM'),
    (212, 'SD', 'Dance Hall Snare', 'PCM', 'PCM'),
    (213, 'SD', 'EDM 909 Snare1', 'PCM', 'PCM'),
    (214, 'SD', 'EDM 909 Snare2', 'PCM', 'PCM'),
    (215, 'SD', '106 Snare1', 'PCM', 'PCM'),
    (216, 'SD', 'Hi Snare', 'PCM', 'PCM'),
    (217, 'SD', 'DA Chamber Snare', 'PCM', 'PCM'),
    (218, 'SD', 'DA Punchy Snare', 'PCM', 'PCM'),
    (219, 'SD', 'Dubstep Snare', 'PCM', 'PCM'),
    (220, 'SD', 'Big Room Snare1', 'PCM', 'PCM'),
    (221, 'SD', 'MG888 Snare1', 'PCM', 'PCM'),
    (222, 'SD', 'Sat Snare', 'PCM', 'PCM'),
    (223, 'SD', 'Tone&SynthSnare', 'PCM', 'PCM'),
    (224, 'SD', '106 Snare2', 'PCM', 'PCM'),
    (225, 'SD', '909 Dist. Snare', 'PCM', 'PCM'),
    (226, 'SD', '626 Dist. Snare1', 'PCM', 'TR-626'),
    (227, 'SD', '626 Dist. Snare2', 'PCM', 'TR-626'),
    (228, 'SD', 'Big Room Snare2', 'PCM', 'PCM'),
    (229, 'SD', 'Noise Snare', 'PCM', 'PCM'),
    (230, 'SD', 'Trap Snare', 'PCM', 'PCM'),
    (231, 'SD', 'Analog Snare1', 'PCM', 'PCM'),
    (232, 'SD', 'Analog Snare2', 'PCM', 'PCM'),
    (233, 'SD', 'Analog Snare3', 'PCM', 'PCM'),
    (234, 'SD', 'Modular Snare', 'PCM', 'PCM'),
    (235, 'SD', 'Layered Snare', 'PCM', 'PCM'),
    (236, 'SD', 'MG888 Snare2', 'PCM', 'PCM'),
    (237, 'SD', 'Snare & RealClap', 'PCM', 'PCM'),
    (238, 'SD', 'Snare&FingerSnap', 'PCM', 'PCM'),
    (239, 'SD', 'Snare & Syn.Clap', 'PCM', 'PCM'),
    (240, 'SD', 'Pure Phat Snare', 'PCM', 'PCM'),
    (241, 'SD', 'Snare & DistClap', 'PCM', 'PCM'),
    (242, 'SD', 'EDM Snare', 'PCM', 'PCM'),
    (243, 'SD', 'EDM Snare&Clap1', 'PCM', 'PCM'),
    (244, 'SD', 'EDM Snare&Clap2', 'PCM', 'PCM'),
    (245, 'SD', '909 Dist.Clap', 'PCM', 'PCM'),
    (246, 'SD', 'Industrial Snare', 'PCM', 'PCM'),
    (247, 'SD', 'Ring Snare', 'PCM', 'PCM'),
    (248, 'SD', 'Snare Scratch', 'PCM', 'PCM'),
    (249, 'TOM', '626 Low Tom1', 'PCM', 'TR-626'),
    (250, 'TOM', '626 Mid Tom1', 'PCM', 'TR-626'),
    (251, 'TOM', '626 High Tom1', 'PCM', 'TR-626'),
    (252, 'TOM', '626 Low Tom2', 'PCM', 'TR-626'),
    (253, 'TOM', '626 Mid Tom2', 'PCM', 'TR-626'),
    (254, 'TOM', '626 High Tom2', 'PCM', 'TR-626'),
    (255, 'TOM', 'Natural Tom', 'PCM', 'PCM'),
    (256, 'TOM', 'Can Tom', 'PCM', 'PCM'),
    (257, 'TOM', 'Analog Tom', 'PCM', 'PCM'),
    (258, 'TOM', 'Modular Tom', 'PCM', 'PCM'),
    (259, 'TOM', 'MG888 Low Tom', 'PCM', 'PCM'),
    (260, 'TOM', 'MG888 High Tom', 'PCM', 'PCM'),
    (261, 'TOM', 'Sat Mod Low Tom', 'PCM', 'PCM'),
    (262, 'TOM', 'Sat Mod High Tom', 'PCM', 'PCM'),
    (263, 'RS', '626 Rim Shot', 'PCM', 'TR-626'),
    (264, 'RS', 'Cross Stick', 'PCM', 'PCM'),
    (265, 'RS', 'Wild Stick', 'PCM', 'PCM'),
    (266, 'RS', 'Lo-Fi Rim', 'PCM', 'PCM'),
    (267, 'RS', 'Real Rim', 'PCM', 'PCM'),
    (268, 'RS', 'MG888 Rim', 'PCM', 'PCM'),
    (269, 'RS', 'MG888 TrRim', 'PCM', 'PCM'),
    (270, 'RS', 'MG888 TrRimFlam', 'PCM', 'PCM'),
    (271, 'HC', '626 Hand Clap', 'PCM', 'TR-626'),
    (272, 'HC', 'Claps Real', 'PCM', 'PCM'),
    (273, 'HC', 'Poly Clap', 'PCM', 'PCM'),
    (274, 'HC', 'Clap Stop', 'PCM', 'PCM'),
    (275, 'HC', 'Lacunal Clap', 'PCM', 'PCM'),
    (276, 'HC', 'Clap&FingerSnap', 'PCM', 'PCM'),
    (277, 'HC', 'EDM Clap', 'PCM', 'PCM'),
    (278, 'HC', 'Analog Clap1', 'PCM', 'PCM'),
    (279, 'HC', 'Analog Clap2', 'PCM', 'PCM'),
    (280, 'HC', 'Analog Clap3', 'PCM', 'PCM'),
    (281, 'HC', 'MG888 Clap', 'PCM', 'PCM'),
    (282, 'HC', 'MG888 MetalClap', 'PCM', 'PCM'),
    (283, 'HC', 'Afro Clap', 'PCM', 'PCM'),
    (284, 'HC', 'Reverse Clap', 'PCM', 'PCM'),
    (285, 'HC', 'Hip Hop Clap', 'PCM', 'PCM'),
    (286, 'HC', 'Craaak', 'PCM', 'PCM'),
    (287, 'HC', 'Scratch Clap', 'PCM', 'PCM'),
    (288, 'HC', 'Finger Snap1', 'PCM', 'PCM'),
    (289, 'HC', 'Finger Snap2', 'PCM', 'PCM'),
    (290, 'HC', 'StereoFingerSnap', 'PCM', 'PCM'),
    (291, 'CH_OH', '626 Closed HH', 'PCM', 'TR-626'),
    (292, 'CH_OH', '626 Open HH', 'PCM', 'TR-626'),
    (293, 'CH_OH', 'Med Closed HH', 'PCM', 'PCM'),
    (294, 'CH_OH', 'Med Open HH', 'PCM', 'PCM'),
    (295, 'CH_OH', 'Dry Closed HH', 'PCM', 'PCM'),
    (296, 'CH_OH', 'Dry Open HH', 'PCM', 'PCM'),
    (297, 'CH_OH', 'Comp Closed HH', 'PCM', 'PCM'),
    (298, 'CH_OH', 'Comp Open HH', 'PCM', 'PCM'),
    (299, 'CH_OH', 'Lo-Bit Closed HH', 'PCM', 'PCM'),
    (300, 'CH_OH', 'Lo-Bit Open HH', 'PCM', 'PCM'),
    (301, 'CH_OH', 'Closed 8bit HH', 'PCM', 'PCM'),
    (302, 'CH_OH', 'ShortNoiseMid HH', 'PCM', 'PCM'),
    (303, 'CH_OH', 'Sat HH', 'PCM', 'PCM'),
    (304, 'CH_OH', 'MG888 HH', 'PCM', 'PCM'),
    (305, 'CH_OH', 'Modular HH', 'PCM', 'PCM'),
    (306, 'CH_OH', 'Jazz Closed HH', 'PCM', 'PCM'),
    (307, 'CH_OH', 'Open Hard HH', 'PCM', 'PCM'),
    (308, 'CH_OH', 'Hi Open HH', 'PCM', 'PCM'),
    (309, 'CH_OH', 'Openopen HH', 'PCM', 'PCM'),
    (310, 'CH_OH', 'Vintage HH', 'PCM', 'PCM'),
    (311, 'CH_OH', 'Vinyl Open HH', 'PCM', 'PCM'),
    (312, 'CH_OH', 'Analog Closed HH', 'PCM', 'PCM'),
    (313, 'CH_OH', 'Analog Open HH', 'PCM', 'PCM'),
    (314, 'CH_OH', 'Sat Closed HH', 'PCM', 'PCM'),
    (315, 'CH_OH', 'Sat Open HH', 'PCM', 'PCM'),
    (316, 'CC_RC', '626 Crash Cymbal', 'PCM', 'TR-626'),
    (317, 'CC_RC', '626 Ride Cymbal', 'PCM', 'TR-626'),
    (318, 'CC_RC', '626 Ride Cup', 'PCM', 'TR-626'),
    (319, 'CC_RC', '626 China Cymbal', 'PCM', 'TR-626'),
    (320, 'CC_RC', 'Standard16 Crash', 'PCM', 'PCM'),
    (321, 'CC_RC', 'StandardRideEdge', 'PCM', 'PCM'),
    (322, 'CC_RC', 'Stereo Cymbal', 'PCM', 'PCM'),
    (323, 'PERC1', '626MuteHighConga', 'PCM', 'TR-626'),
    (324, 'PERC1', '626OpenHighConga', 'PCM', 'TR-626'),
    (325, 'PERC1', '626 Low Conga', 'PCM', 'TR-626'),
    (326, 'PERC1', 'Sat Sine Conga', 'PCM', 'PCM'),
    (327, 'PERC1', 'Sat Sine Bongo', 'PCM', 'PCM'),
    (328, 'PERC1', '626 High Timbale', 'PCM', 'TR-626'),
    (329, 'PERC1', '626 Low Timbale', 'PCM', 'TR-626'),
    (330, 'PERC1', 'High Timbale', 'PCM', 'PCM'),
    (331, 'PERC1', 'Low Timbale', 'PCM', 'PCM'),
    (332, 'PERC1', 'SambaPercussion1', 'PCM', 'PCM'),
    (333, 'PERC1', 'Samba Bateria', 'PCM', 'PCM'),
    (334, 'PERC1', 'SambaPercussion2', 'PCM', 'PCM'),
    (335, 'PERC2', '626 Claves', 'PCM', 'TR-626'),
    (336, 'PERC2', 'High Claves', 'PCM', 'PCM'),
    (337, 'PERC2', 'MG888 Claves', 'PCM', 'PCM'),
    (338, 'PERC2', 'Ohkawa', 'PCM', 'PCM'),
    (339, 'PERC2', 'Block', 'PCM', 'PCM'),
    (340, 'PERC2', 'Castanets', 'PCM', 'PCM'),
    (341, 'PERC3', '626 Shaker', 'PCM', 'TR-626'),
    (342, 'PERC3', 'Real Shaker', 'PCM', 'PCM'),
    (343, 'PERC3', 'Analog Shaker', 'PCM', 'PCM'),
    (344, 'PERC3', '626 Tambourine', 'PCM', 'TR-626'),
    (345, 'PERC3', 'Tambourine', 'PCM', 'PCM'),
    (346, 'SYNTH1', 'Chekere', 'PCM', 'PCM'),
    (347, 'PERC3', 'AfroDrum Rat', 'PCM', 'PCM'),
    (348, 'PERC4', '626 Cowbell', 'PCM', 'TR-626'),
    (349, 'PERC4', 'Cowbell', 'PCM', 'PCM'),
    (350, 'PERC4', 'Tin Cowbell', 'PCM', 'PCM'),
    (351, 'PERC4', '626 High Agogo', 'PCM', 'TR-626'),
    (352, 'PERC4', '626 Low Agogo', 'PCM', 'TR-626'),
    (353, 'PERC4', 'Open Triangle', 'PCM', 'PCM'),
    (354, 'PERC4', 'Funky Triangle', 'PCM', 'PCM'),
    (355, 'PERC5', 'Jingle Bell', 'PCM', 'PCM'),
    (356, 'PERC5', 'Udu Pot Long', 'PCM', 'PCM'),
    (357, 'PERC5', 'Udu Pot Short', 'PCM', 'PCM'),
    (358, 'PERC5', 'Udu Pot Mute', 'PCM', 'PCM'),
    (359, 'FX_HIT', 'AnalogMetalPerc1', 'PCM', 'PCM'),
    (360, 'FX_HIT', 'AnalogMetalPerc2', 'PCM', 'PCM'),
    (361, 'FX_HIT', 'Mental Perc', 'PCM', 'PCM'),
    (362, 'FX_HIT', 'Dr.Beat', 'PCM', 'PCM'),
    (363, 'FX_HIT', 'PC-2 Machine', 'PCM', 'PCM'),
    (364, 'FX_HIT', 'Feedback Stab', 'PCM', 'PCM'),
    (365, 'FX_HIT', '1971 SpringBlip', 'PCM', 'PCM'),
    (366, 'FX_HIT', '1971 Doctor', 'PCM', 'PCM'),
    (367, 'FX_HIT', '1971 Phone', 'PCM', 'PCM'),
    (368, 'FX_HIT', 'Modular Sweep', 'PCM', 'PCM'),
    (369, 'FX_HIT', 'Modular FX Dly', 'PCM', 'PCM'),
    (370, 'FX_HIT', 'PC-2 Spacers', 'PCM', 'PCM'),
    (371, 'FX_HIT', 'Ring FX', 'PCM', 'PCM'),
    (372, 'FX_HIT', '1971 Fall', 'PCM', 'PCM'),
    (373, 'FX_HIT', 'Modular FX1', 'PCM', 'PCM'),
    (374, 'FX_HIT', 'Modular FX2', 'PCM', 'PCM'),
    (375, 'FX_HIT', 'MG888 FutureShot', 'PCM', 'PCM'),
    (376, 'FX_HIT', 'SH2 S Zap', 'PCM', 'PCM'),
    (377, 'FX_HIT', '1971 Dong', 'PCM', 'PCM'),
    (378, 'FX_HIT', 'Sat Stab', 'PCM', 'PCM'),
    (379, 'FX_HIT', 'Pong1', 'PCM', 'PCM'),
    (380, 'FX_HIT', 'Pong2', 'PCM', 'PCM'),
    (381, 'FX_HIT', 'Boing', 'PCM', 'PCM'),
    (382, 'FX_HIT', 'Jungle Beep', 'PCM', 'PCM'),
    (383, 'FX_HIT', 'Tape Stop', 'PCM', 'PCM'),
    (384, 'FX_HIT', 'Techno Scene', 'PCM', 'PCM'),
    (385, 'FX_HIT', 'P.Phatt Hit', 'PCM', 'PCM'),
    (386, 'FX_HIT', 'Hit & Drum', 'PCM', 'PCM'),
    (387, 'FX_HIT', 'Spoon Hit', 'PCM', 'PCM'),
    (388, 'FX_HIT', 'Elec Sizzle', 'PCM', 'PCM'),
    (389, 'FX_HIT', 'Industrial Hit1', 'PCM', 'PCM'),
    (390, 'FX_HIT', 'Industrial Hit2', 'PCM', 'PCM'),
    (391, 'FX_HIT', 'PCM Press', 'PCM', 'PCM'),
    (392, 'FX_HIT', 'Thrill', 'PCM', 'PCM'),
    (393, 'FX_HIT', 'ElectricDunk', 'PCM', 'PCM'),
    (394, 'FX_HIT', 'Construction', 'PCM', 'PCM'),
    (395, 'FX_HIT', 'Sawing', 'PCM', 'PCM'),
    (396, 'FX_HIT', 'Compress Start', 'PCM', 'PCM'),
    (397, 'FX_HIT', 'Jack Hammer', 'PCM', 'PCM'),
    (398, 'FX_HIT', 'Machine Noise', 'PCM', 'PCM'),
    (399, 'FX_HIT', 'Metal Bang', 'PCM', 'PCM'),
    (400, 'FX_HIT', 'Metallic Shot', 'PCM', 'PCM'),
    (401, 'FX_HIT', 'Tom Noise', 'PCM', 'PCM'),
    (402, 'FX_HIT', 'Hi Dist Short', 'PCM', 'PCM'),
    (403, 'FX_HIT', 'DigiAttack', 'PCM', 'PCM'),
    (404, 'FX_HIT', 'Vinyl Noise', 'PCM', 'PCM'),
    (405, 'FX_HIT', 'Glass', 'PCM', 'PCM'),
    (406, 'FX_HIT', 'Rev 626 Crash', 'PCM', 'PCM'),
    (407, 'FX_HIT', 'Rev 626 Ride', 'PCM', 'PCM'),
    (408, 'FX_HIT', 'Rev 626 Cup', 'PCM', 'PCM'),
    (409, 'FX_HIT', 'Rev 626 China', 'PCM', 'PCM'),
    (410, 'FX_HIT', 'Rev Stereo Cym', 'PCM', 'PCM'),
    (411, 'FX_HIT', 'Rev Analog Tom', 'PCM', 'PCM'),
    (412, 'FX_HIT', 'Rev Natural Tom', 'PCM', 'PCM'),
    (413, 'FX_HIT', 'Flute FX', 'PCM', 'PCM'),
    (414, 'FX_HIT', 'Tube FX', 'PCM', 'PCM'),
    (415, 'FX_HIT', 'Voice Bells', 'PCM', 'PCM'),
    (416, 'VOICE', 'Ouh', 'PCM', 'PCM'),
    (417, 'VOICE', 'Hoo!', 'PCM', 'PCM'),
    (418, 'VOICE', 'Uhha', 'PCM', 'PCM'),
    (419, 'VOICE', 'Eh', 'PCM', 'PCM'),
    (420, 'VOICE', 'Oh!', 'PCM', 'PCM'),
    (421, 'VOICE', 'DA Break', 'PCM', 'PCM'),
    (422, 'VOICE', 'DA VT Check', 'PCM', 'PCM'),
    (423, 'VOICE', 'DA VT Hey', 'PCM', 'PCM'),
    (424, 'VOICE', 'DA VT Oh', 'PCM', 'PCM'),
    (425, 'VOICE', 'DA VP Go', 'PCM', 'PCM'),
    (426, 'VOICE', 'DA VP Move', 'PCM', 'PCM'),
    (427, 'VOICE', 'Voice FX', 'PCM', 'PCM'),
    (428, 'VOICE', 'Vocoder A', 'PCM', 'PCM'),
    (429, 'VOICE', 'Vocoder Dance', 'PCM', 'PCM'),
    (430, 'VOICE', 'Aah Formant', 'PCM', 'PCM'),
    (431, 'VOICE', 'Eeh Formant', 'PCM', 'PCM'),
    (432, 'VOICE', 'Iih Formant', 'PCM', 'PCM'),
    (433, 'VOICE', 'Ooh Formant', 'PCM', 'PCM'),
    (434, 'VOICE', 'Uuh Formant', 'PCM', 'PCM'),
    (435, 'SYNTH1', 'Soft Pad', 'PCM', 'PCM'),
    (436, 'SYNTH1', 'Synth Strings', 'PCM', 'PCM'),
    (437, 'SYNTH1', 'ElectroHouse Syn', 'PCM', 'PCM'),
    (438, 'SYNTH1', 'EDM Bend Up Lead', 'PCM', 'PCM'),
    (439, 'SYNTH1', 'EDM Voice Lead', 'PCM', 'PCM'),
    (440, 'SYNTH1', 'Dubstep Lead', 'PCM', 'PCM'),
    (441, 'SYNTH1', 'Percussive Lead', 'PCM', 'PCM'),
    (442, 'SYNTH1', 'FutureHouseLead1', 'PCM', 'PCM'),
    (443, 'SYNTH1', 'FutureHouseLead2', 'PCM', 'PCM'),
    (444, 'SYNTH1', 'Synth Calliope', 'PCM', 'PCM'),
    (445, 'SYNTH1', 'Synth Pluck1', 'PCM', 'PCM'),
    (446, 'SYNTH1', 'Synth Pluck2', 'PCM', 'PCM'),
    (447, 'SYNTH1', 'Trap Synth1', 'PCM', 'PCM'),
    (448, 'SYNTH1', 'Trap Synth2', 'PCM', 'PCM'),
    (449, 'SYNTH1', 'Trap Horn1', 'PCM', 'PCM'),
    (450, 'SYNTH1', 'Trap Horn2', 'PCM', 'PCM'),
    (451, 'SYNTH2', 'OSC Sine Low', 'PCM', 'PCM'),
    (452, 'SYNTH2', 'OSC Sine High', 'PCM', 'PCM'),
    (453, 'SYNTH2', 'OSC Cosine Low', 'PCM', 'PCM'),
    (454, 'SYNTH2', 'OSC Cosine High', 'PCM', 'PCM'),
    (455, 'SYNTH2', 'OSC Tri1 Low', 'PCM', 'PCM'),
    (456, 'SYNTH2', 'OSC Tri1 High', 'PCM', 'PCM'),
    (457, 'SYNTH2', 'OSC Tri2 Low', 'PCM', 'PCM'),
    (458, 'SYNTH2', 'OSC Tri2 High', 'PCM', 'PCM'),
    (459, 'SYNTH2', 'OSC Square Low', 'PCM', 'PCM'),
    (460, 'SYNTH2', 'OSC Square High', 'PCM', 'PCM'),
    (461, 'SYNTH2', 'OSC Pulse1 Low', 'PCM', 'PCM'),
    (462, 'SYNTH2', 'OSC Pulse1 High', 'PCM', 'PCM'),
    (463, 'SYNTH2', 'OSC Pulse2 Low', 'PCM', 'PCM'),
    (464, 'SYNTH2', 'OSC Pulse2 High', 'PCM', 'PCM'),
    (465, 'SYNTH2', 'OSC Saw Low', 'PCM', 'PCM'),
    (466, 'SYNTH2', 'OSC Saw High', 'PCM', 'PCM'),
    (467, 'SYNTH2', 'Detune Saw Low', 'PCM', 'PCM'),
    (468, 'SYNTH2', 'Detune Saw High', 'PCM', 'PCM'),
    (469, 'SYNTH2', 'Super Saw1', 'PCM', 'PCM'),
    (470, 'SYNTH2', 'Super Saw2', 'PCM', 'PCM'),
    (471, 'SYNTH2', 'Super Saw1 5th', 'PCM', 'PCM'),
    (472, 'SYNTH2', 'Super Saw2 5th', 'PCM', 'PCM'),
    (473, 'SYNTH2', 'White Noise1', 'PCM', 'PCM'),
    (474, 'SYNTH2', 'White Noise2', 'PCM', 'PCM'),
    (475, 'SYNTH2', 'White Noise3', 'PCM', 'PCM'),
    (476, 'BASS', 'Sustnd808Bs', 'PCM', 'PCM'),
    (477, 'BASS', 'DistSustnd808Bs1', 'PCM', 'PCM'),
    (478, 'BASS', 'DistSustnd808Bs2', 'PCM', 'PCM'),
    (479, 'BASS', 'DistSustnd808Bs3', 'PCM', 'PCM'),
    (480, 'BASS', 'DistSustnd808Bs4', 'PCM', 'PCM'),
    (481, 'BASS', 'Heavy Future Bs1', 'PCM', 'PCM'),
    (482, 'BASS', 'Heavy Future Bs2', 'PCM', 'PCM'),
    (483, 'BASS', 'Organ Bass', 'PCM', 'PCM'),
    (484, 'BASS', 'Percussive Bass', 'PCM', 'PCM'),
    (485, 'BASS', 'Prog.Trance Bass', 'PCM', 'PCM'),
    (486, 'BASS', 'Deep SH Bass', 'PCM', 'PCM'),
    (487, 'BASS', 'Electro House Bs', 'PCM', 'PCM'),
    (488, 'BASS', 'Yeah Bass', 'PCM', 'PCM'),
    (489, 'BASS', 'Yigh Bass', 'PCM', 'PCM'),
    (490, 'BASS', 'Mute Bass', 'PCM', 'PCM'),
    (491, 'SCALED', 'Ac.Piano Mid', 'PCM', 'PCM'),
    (492, 'SCALED', 'Ac.Piano High', 'PCM', 'PCM'),
    (493, 'SCALED', 'E.Piano Mid', 'PCM', 'PCM'),
    (494, 'SCALED', 'E.Piano High', 'PCM', 'PCM'),
    (495, 'SCALED', 'Kalimba Mid', 'PCM', 'PCM'),
    (496, 'SCALED', 'Kalimba High', 'PCM', 'PCM'),
    (497, 'SCALED', 'Tropical Mallet', 'PCM', 'PCM'),
    (498, 'SCALED', 'Pizzi Techno', 'PCM', 'PCM'),
    (499, 'SCALED', 'Strings Attack', 'PCM', 'PCM'),
    (500, 'SCALED', 'LA BrassLow Oct', 'PCM', 'PCM'),
    (501, 'SCALED', 'LA BrassHigh Oct', 'PCM', 'PCM'),
    (502, 'SCALED', 'LA BrassLow 5th', 'PCM', 'PCM'),
    (503, 'SCALED', 'LA BrassHigh 5th', 'PCM', 'PCM'),
    (504, 'SCALED', 'Didgeridoo', 'PCM', 'PCM'),
    (505, 'CHORD', 'HouseChordPiano', 'PCM', 'PCM'),
    (506, 'CHORD', 'E.Piano Maj 9th', 'PCM', 'PCM'),
    (507, 'CHORD', 'E.Piano Hit', 'PCM', 'PCM'),
    (508, 'CHORD', 'E.Piano Maj 11th', 'PCM', 'PCM'),
    (509, 'CHORD', 'Strings Maj 11th', 'PCM', 'PCM'),
    (510, 'CHORD', 'Open Str', 'PCM', 'PCM'),
    (511, 'CHORD', 'Wah Mute', 'PCM', 'PCM'),
    (512, 'CHORD', 'Percussive Chord', 'PCM', 'PCM'),
    (513, 'CHORD', 'DA D50 Chord', 'PCM', 'PCM'),
    (514, 'CHORD', 'Atmosphere', 'PCM', 'PCM'),
    (515, 'CHORD', 'DA SH Chord', 'PCM', 'PCM'),
    (516, 'CHORD', 'SoftPad minor7th', 'PCM', 'PCM'),
    (517, 'CHORD', 'SoftPad major7th', 'PCM', 'PCM'),
    (518, 'CHORD', 'SoftPad 7th', 'PCM', 'PCM'),
    (519, 'CHORD', 'Syn.Str minor7th', 'PCM', 'PCM'),
    (520, 'CHORD', 'Syn.Str major7th', 'PCM', 'PCM'),
    (521, 'CHORD', 'Syn.Str 7th', 'PCM', 'PCM'),
]

POR_ID = {t[0]: t for t in TONES}


def nome(tone_id):
    """Nome do tone, ou None se o id nao existe."""
    t = POR_ID.get(tone_id)
    return t[2] if t else None
